import Head from 'next/head';
import * as Styles from '@/styles/styled';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bloguinho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Styles.Container>
        <h2>Bloguinho</h2>
      </Styles.Container>
    </>
  );
}
